version: '3'

# This docker-compose file is not for running the app. Instead, it's for building the application
# within a container. This has the benefit of building in a known environment so that:
#   1) Parameters such as output directory can be automatically set correctly
#   2) A developer can have confidence that the build process (and environment) they're using will be
#      identical to what's used by the CI system. It will never build 'only on my machine'
services:
  ci-build:
    # This base image includes .NET Core build tools
    image: microsoft/aspnetcore-build:2.0.0

    # Volume mount the src folder so that the Docker container can reach out of its container to access
    # the solution source and output directory.
    volumes:
      - .:/src
    working_dir: /src
    environment:
      - DockerPublishing=true

    # The build command. Can be updated, as necessary (though, be sure to update docker-compose accordingly if output dir changes)
    command: /bin/bash -c "dotnet restore ./CustomersDemo-2017.sln && dotnet publish ./src/CustomersAPI/CustomersAPI.csproj -c Release -o ./obj/Docker/publish && dotnet publish ./src/CustomersMVC/CustomersMVC.csproj -c Release -o ./obj/Docker/publish"
