version: '3'

services:
  # Each Docker container that's part of the app
  # should be listed in docker-compose
  customersapi:
    # Name for the Docker container
    # Note that this will also be the name that other containers
    # can use to refer to this one from within the Docker-compose cluster
    image: customersapi
    build:
      context: ./src/CustomersAPI
      dockerfile: Dockerfile
    ports:
      # Normally, this internal API wouldn't need its port exposed, but I do so here
      # so that I can demo hitting it in a container
      - "8080:5000"

  customersmvc:
    image: customersmvc
    build:
      context: ./src/CustomersMVC
      dockerfile: Dockerfile
    depends_on:
      - customersapi
    environment:
      - CustomersAPIService:Url=http://customersapi:5000
    ports:
      - "80:80"
